name: hstx-node-sdk CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ '10', '8' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com
    - name: Install dependencies
      run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}